# SPDX-FileCopyrightText: 2024 itiquette/git-provider-sync
#
# SPDX-License-Identifier: CC0-1.0

# Configuration version for golangci-lint
version: 2

output:
  formats:
    colored-line-number:
      path: stderr
issues:
  exclude-dirs:
    - generated
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable basic linters only for now
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - whitespace
