# SPDX-FileCopyrightText: 2025 itiquette/git-provider-sync
#
# SPDX-License-Identifier: CC0-1.0

---
name: Golang Lint
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  golangci:
    name: GolangCI-Lint analysis
    runs-on: ubuntu-latest
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "stable"
          cache: false

      - name: Generate mocks
        run: |
          go install github.com/vektra/mockery/v2@v2.53.3
          go mod tidy
          ./scripts/generatemock.sh

      - name: golangci-Lint analysis
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          skip-cache: true
          skip-save-cache: true
          version: latest
