# SPDX-FileCopyrightText: 2025 itiquette/git-provider-sync
#
# SPDX-License-Identifier: CC0-1.0

---
name: Golang Lint
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  golangci:
    name: GolangCI-Lint analysis
    runs-on: ubuntu-latest
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "stable"
          cache: false

      - name: Generate mocks
        run: |
          go install github.com/vektra/mockery/v2@v2.53.3
          go mod tidy
          ./scripts/generatemock.sh

      - name: golangci-Lint analysis
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          skip-cache: true
          skip-save-cache: true
          version: latest
