# SPDX-FileCopyrightText: 2025 itiquette/git-provider-sync
#
# SPDX-License-Identifier: CC0-1.0

---
name: Golang Test

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "stable"
          cache: false

      - name: Go test run
        run: |
          go mod tidy
          # shellcheck disable=SC2046
          go test -count=1 $(go list './...' | grep -v generated) -v -coverprofile=coverage.txt 
          go tool cover -func=coverage.txt -o=coverage.out
          # shellcheck disable=SC2002
          # shellcheck disable=SC2086
          echo "COVERAGE=$(cat coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      # - name: Create Coverage Badge
      #   uses: schneegans/dynamic-badges-action@v1.7.0
      #   with:
      #     auth: ${{ secrets.GIST_SECRET }}
      #     gistID: 87d513c639cf65c02ecc31c1670cbcd1
      #     filename: go-coverage.json
      #     label: Coverage
      #     message: ${{ env.COVERAGE }}%
      #     color: purple
