# SPDX-FileCopyrightText: 2025 itiquette/git-provider-sync
#
# SPDX-License-Identifier: CC0-1.0

---
name: Golang Test

on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "stable"
          cache: false

      - name: Go test run
        run: |
          go mod tidy
          # shellcheck disable=SC2046
          go test -count=1 $(go list './...' | grep -v generated) -v -coverprofile=coverage.txt 
          go tool cover -func=coverage.txt -o=coverage.out
          # shellcheck disable=SC2002
          # shellcheck disable=SC2086
          echo "COVERAGE=$(cat coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      # - name: Create Coverage Badge
      #   uses: schneegans/dynamic-badges-action@v1.7.0
      #   with:
      #     auth: ${{ secrets.GIST_SECRET }}
      #     gistID: 87d513c639cf65c02ecc31c1670cbcd1
      #     filename: go-coverage.json
      #     label: Coverage
      #     message: ${{ env.COVERAGE }}%
      #     color: purple
